version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/homebanking
      - DATABASE_USERNAME=homebankingapp
      - DATABASE_PASSWORD=123456
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=homebanking
      - POSTGRES_USER=homebankingapp
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
